def _pick(source, keys):
    out = {}
    for key in keys:
        if isinstance(key, tuple):
            out_key, src_key = key
        else:
            out_key = key
            src_key = key
        out[out_key] = source[src_key]
    return out


def build_route_dependencies(symbols):
    live_keys = [
        "db",
        "or_",
        "AI_ENABLED",
        "ATTACK_SEVERITY",
        ("require_roles", "_require_roles"),
        "LIVE_EVENTS",
        "received_logs",
        "LiveLog",
        "LiveFilter",
        "AlertRule",
        "Simulation",
        "Case",
        "CaseNote",
        "CaseAttachment",
        ("infer_stage", "_infer_stage"),
        ("normalize_severity", "_normalize_severity"),
        ("extract_iocs", "_extract_iocs"),
        ("record_indicator", "_record_indicator"),
        "map_log_to_event",
        ("index_live_log", "_index_live_log"),
        ("record_threat_discovery", "_record_threat_discovery"),
        ("recommendations_for_event", "_recommendations_for_event"),
        ("expand_chain_event", "_expand_chain_event"),
        ("aggregate_live_chain", "_aggregate_live_chain"),
        ("build_live_analysis", "_build_live_analysis"),
        ("match_alert_rule", "_match_alert_rule"),
        ("create_case_from_event_internal", "_create_case_from_event"),
        ("record_audit", "_record_audit"),
        "update_analytics_report",
    ]
    cases_keys = [
        "db",
        "Case",
        "CaseNote",
        "CaseAttachment",
        "CaseEvent",
        "CaseChecklistItem",
        "Simulation",
        "User",
        "CASE_TEMPLATES",
        "incident_playbooks",
        ("severity_from_score", "_severity_from_score"),
        ("ensure_case_checklist", "_ensure_case_checklist"),
        ("weekly_report_data", "_weekly_report_data"),
        ("record_audit", "_record_audit"),
        ("record_case_event", "_record_case_event"),
        ("build_history", "_build_history"),
    ]
    ops_keys = [
        "db",
        "or_",
        "ThreatSignature",
        "ThreatDiscovery",
        "ThreatSummary",
        "ThreatAdvisory",
        "ThreatSettings",
        "AlertRule",
        "UserWidget",
        "AuditLog",
        "Indicator",
        "IndicatorRelation",
        "RetentionPolicy",
        "User",
        "AI_ENABLED",
        "ai_advisor",
        ("require_roles", "_require_roles"),
        ("get_widget_prefs", "_get_widget_prefs"),
        ("record_audit", "_record_audit"),
        ("build_advisory_trend", "_build_advisory_trend"),
        ("build_threat_summary", "_build_threat_summary"),
        ("build_threat_advisories", "_build_threat_advisories"),
        ("compute_rule_effectiveness", "_compute_rule_effectiveness"),
        ("apply_retention", "_apply_retention"),
    ]
    core_keys = [
        "_run_due_schedules",
        "_build_history",
        "calculate_analytics",
        "calculate_upgrade_roi",
        "SavedSearch",
        "SimulationPreset",
        "SimulationSchedule",
        "User",
        "UPGRADES",
        "incident_playbooks",
        "AI_ENABLED",
        "Case",
        "_get_widget_prefs",
        "search_all",
        "module_default_settings",
        "module_settings_for_user",
        "FeatureModuleSetting",
        "feature_module_preview",
        "_compute_rule_effectiveness",
        "CaseNote",
        "CaseEvent",
        "Simulation",
        "Indicator",
        "LIVE_EVENTS",
        "_parse_event_time",
        "FEATURE_MODULES",
        "_require_roles",
        "IndicatorRelation",
        "ai_advisor",
        "_build_live_brief",
        "_fallback_recommendation_explain",
        "_fallback_next_steps",
        "_fallback_case_summary",
        "_fallback_root_cause",
        "_fallback_triage",
        "_run_simulation_for_user",
        "update_analytics_report",
        "_severity_from_score",
        "MITRE_ATTACK_MAPPING",
        "_ioc_technique_cooccurrence",
        "db",
        "_resource_monitoring",
        "_kpi_dashboard_rows",
    ]
    return {
        "live": _pick(symbols, live_keys),
        "cases": _pick(symbols, cases_keys),
        "ops": _pick(symbols, ops_keys),
        "core": _pick(symbols, core_keys),
    }
